services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.
    ProjetNormandie\EmailBundle\:
        resource: '../../*'
        exclude: '../../{Admin,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    projet_normandie_email.swiftmailer.mapper:
        public: true
        class: ProjetNormandie\EmailBundle\Mapper\SwiftMailerMapper
    ProjetNormandie\EmailBundle\Service\Mailer:
        class: ProjetNormandie\EmailBundle\Service\Mailer
        arguments: [
            "@swiftmailer.mailer.default",
            "@projet_normandie_email.swiftmailer.mapper",
            "@=service('doctrine.orm.default_entity_manager')",
            "%projetnormandie_email.from%"
            ]
