services:
    projet_normandie_email.plugin:
        class: ProjetNormandie\EmailBundle\Plugin\SwiftMailerDatabaseLogger
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: swiftmailer.default.plugin }
