services:
    projet_normandie_email.swiftmailer.mapper:
        class: ProjetNormandie\EmailBundle\Mapper\SwiftMailerMapper
    projet_normandie_email.mailer:
        class: ProjetNormandie\EmailBundle\Service\Mailer
        arguments: ["@swiftmailer.mailer.default", "@projet_normandie_email.swiftmailer.mapper", "%projetnormandie_email.from%"]
